import type { Metadata } from 'next';
import { Arsenal } from 'next/font/google';

import { DesktopNavigation } from '@widgets/navigation-menu';

import { SmoothScrollProvider } from './_providers';

import './globals.css';

const arsenalFont = Arsenal({
  weight: ['400', '700'],
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={arsenalFont.className}>
        <SmoothScrollProvider>
          <header className="flex items-center px-8 py-4">
            <div>logo</div>
            <div className="ml-auto">
              <DesktopNavigation />
            </div>
          </header>
          {children}
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
